name = "lsp"
version = "0.0"
executable = "idris2-lsp"

[ source ]
owner = "idris-community"
repo = "idris2-lsp"
rev = "12b4c27481fd7e3b32d2afba5bb11ff7b7e324d8"
sha256 = "88Z7Gd6EwDrHUByZ5Kw52kY5kvAwkgNeuZQ7KK7RHk8="

[ depends ]
idrisLibs = [ "idris2api" ]
buildInputs = [ ]

[ test ]
enable = true
preTest = """
# macOS does not allow direct access to /tmp
for file in tests/Makefile tests/lsp/message001/*; do
  sed -i "s|/tmp/test-lsp.idr|$(pwd)/tests/test-lsp.idr|g" $file;
done

# Apply codegen patches to the test binary so it can run in nix
make -C tests testbin
patchFile tests/build/exec/runtests
"""
command = "make -C tests INTERACTIVE= "
