name = "lsp"
version = "0.0"
executable = "idris2-lsp"

[ source ]
owner = "idris-community"
repo = "idris2-lsp"
rev = "12b4c27481fd7e3b32d2afba5bb11ff7b7e324d8"
sha256 = "88Z7Gd6EwDrHUByZ5Kw52kY5kvAwkgNeuZQ7KK7RHk8="

[ depends ]
idrisLibs = [ "idris2api" ]
buildInputs = [ ]

[ test ]
enable = true
command = """
make -C tests testbin
patchFile tests/build/exec/runtests
make -C tests INTERACTIVE=
"""
