name = "pretty-show"
version = "0.2.0"

[ source ]
owner = "stefan-hoeck"
repo = "idris2-pretty-show"
rev = "1c872b6b0dfcb3f2cd73ead773fa267c04780eda"
sha256 = "2Li9x4HvBUGZEqFlysGafQ06I2kbKyMdz2WiJbnJMZI="

[ depends ]
idrisLibs = [ "elab-util", "sop" ]

[ test ]
enable = true
command = """
idris2 --build test.ipkg
build/exec/runTest
"""
