name = "pretty-show"
version = "0.2.0"

[ source ]
owner = "stefan-hoeck"
repo = "idris2-pretty-show"
rev = "28d83af17c7f281cf49e593d4283d1b877788231"
sha256 = "gOLFijoE7zJVlbPAlwMLLy/fYTE4++CQAQjsfd9EisY="

[ depends ]
idrisLibs = [ "elab-util", "sop" ]

[ test ]
enable = true
postTest = "build/exec/runTest"
