name = "readline"
ipkgFile = "samples/FFI-readline/readline.ipkg"

[ source ]
owner = "idris-lang"
repo = "Idris2"
rev = "f255026d1b99934f4418993517eee11c8de8b678"
sha256 = "h7CfQliuH9RnQZ3hrDta3thXqzCMapEIcuqUm4Xdzy8="

[ patch ]
preBuild = """
    # idris-lang/Idris2 (#1179)
    sed -i 's/^\\(#include <readline\\)/#include <stdio.h>\\n\\1/' samples/FFI-readline/readline_glue/idris_readline.c
"""

[ depends ]
buildInputs = [ "readline" ]
