name = "mypkg"
version =  "0.0"

[ source ]
owner = "idris-lang"
repo = "Idris2"
rev = "replace this string with the specific commit hash"
# sha256 = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"

[ depends ]
idrisLibs = [ ]
buildInputs = [ ]
